# Generated by Django 2.2.7 on 2019-11-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('nickname', models.TextField(max_length=10)),
                ('reviews', models.TextField(max_length=256)),
                ('about', models.TextField(max_length=200)),
                ('timezone', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard', models.BooleanField(null=True)),
                ('authenticator', models.BooleanField(null=True)),
                ('sms', models.BooleanField(null=True)),
            ],
        ),
    ]
