# Generated by Django 2.2.6 on 2019-10-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorders',
            name='order_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
