default:
  SECRET_KEY: ""
  DEBUG: true
  ALLOWED_HOSTS: []

heroku:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - kefir331.herokuapp.com

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost